### PR TITLE
Updating plugin to 1.8.8

### PR DESCRIPTION
**Pull request by idoash4**
I have tested everything I could think of and the plugin seems to be working after a few minor fixes. By default a player will be put back into normal mode once he leaves the server. You can change this but keep in mind that server crashes may cause problems. Normal restarts/shutdowns should be fine as all players will be moved back into normal mode and their inventory will be loaded correctly.

### CODE REVIEW

**Comment by ttk2** [comment]
looks good @rourke750  should I merge? Do we have a build server entry for this yet?

**Comment by rourke750** [comment]
@ttk2 http://build.civcraft.co:8080/job/Duties-master/1/

**Comment by ttk2** [comment]
yay!

**Comment by idoash4** [comment]
You can stage this. I think I covered everything in the testing.

**Pull request merged**
